program: train.py
method: grid
metric:
  name: val_f1
  goal: maximize
parameters:
  lr:
    values: [0.001, 0.0005, 0.0001]
  batch_size:
    values: [32]
  seed:
    values: [42, 69, 2]
  fold_id:
    values: [0]
  epochs:
    value: 50
  model_name:
    values: ['efficientnet_b3']
